# Generated by Django 5.1.5 on 2025-02-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_create_room_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
